_schema-version: '3.1'
ID: skillforge-training-platform
version: 1.0.0
description: A simple CAP project.
parameters:
  deploy_mode: html5-repo
  enable-parallel-deployments: true
  subdomain: sap-build-work-zone-zsdt2mzd
build-parameters:
  before-all:
    - builder: custom
      commands:
        - rm -rf build/dist
        - mkdir -p build/dist
        - rm -rf build/ui-deployer
        - mkdir -p build/ui-deployer
    - builder: custom
      commands:
        - npm install --production
        - >-
          bash -c "cds -v | grep 'cds-dk' || npm i --production --no-save
          @sap/cds-dk"
        - bash -c "export PATH=$PATH:$(pwd)/node_modules/.bin"
        - cds build --production
  after-all:
    - builder: custom
      commands:
        - npm install
modules:
  - name: skillforge-training-platform-saplearningcenter.saplearningcenter
    type: html5
    path: app/saplearningcenter.saplearningcenter
    build-parameters:
      builder: custom
      commands:
        - rm -rf dist-zip dist
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - mkdir dist-zip
        - >-
          bash -c "cd dist && npx bestzip
          ../dist-zip/saplearningcentersaplearningcenter.zip *"
      _artifactName: saplearningcentersaplearningcenter.zip
      supported-platforms: []
      build-result: dist-zip
  - name: skillforge-training-platform-db-deployer
    type: hdb
    path: gen/db
    parameters:
      buildpack: nodejs_buildpack
    build-parameters:
      builder: npm
      ignore:
        - node_modules
        - package-lock.json
    requires:
      - name: skillforge-training-platform-service-uaa
      - name: skillforge-training-platform-service-db
  - name: skillforge-training-platform-srv
    type: nodejs
    path: gen/srv
    parameters:
      memory: 256MB
    provides:
      - name: srv-api
        properties:
          srv-url: ${default-url}
    build-parameters:
      builder: npm
      ignore:
        - node_modules
        - package-lock.json
    requires:
      - name: skillforge-training-platform-service-uaa
      - name: skillforge-training-platform-service-db
      - name: skillforge-training-platform-service-destination
      - name: skillforge-training-platform-service-metadata
      - name: skillforge-training-platform-service-connectivity
      - name: skillforge-training-platform-service-logs
  - name: skillforge-training-platform-aux-destinations
    type: com.sap.application.content
    parameters:
      content:
        subaccount:
          existing_destinations_policy: update
          destinations:
            - Authentication: OAuth2UserTokenExchange
              Name: skillforge-training-platform-service-uaa
              ServiceInstanceName: skillforge-training-platform-uaa
              ServiceKeyName: skillforge-training-platform-uaa-key
              sap.cloud.service: lcap.skillforge-training-platform
            - Authentication: OAuth2UserTokenExchange
              Name: skillforge-training-platform-app-srv
              TokenServiceInstanceName: skillforge-training-platform-uaa
              TokenServiceKeyName: skillforge-training-platform-uaa-key
              URL: ~{srv-api/srv-url}
              sap.cloud.service: lcap.skillforge-training-platform
            - Name: skillforge-training-platform-service-html5-apps-repo-host
              ServiceInstanceName: skillforge-training-platform-html5-apps-repo-host
              ServiceKeyName: skillforge-training-platform-html5-apps-repo-host-key
              sap.cloud.service: lcap.skillforge-training-platform
            - Authentication: OAuth2UserTokenExchange
              Name: skillforge-training-platform-SkillForgeService
              TokenServiceInstanceName: skillforge-training-platform-uaa
              TokenServiceKeyName: skillforge-training-platform-uaa-key
              URL: ~{srv-api/srv-url}/service/SkillForgeService
              sap.cloud.service: lcap.skillforge-training-platform
              sap.applicationdevelopment.actions.enabled: false
              sap.build.usage: CAP
              sap.processautomation.enabled: false
              HTML5.DynamicDestination: false
              WebIDEEnabled: false
              MobileEnabled: false
              AppgyverEnabled: false
    build-parameters:
      no-source: true
    requires:
      - name: skillforge-training-platform-service-uaa
        parameters:
          service-key:
            name: skillforge-training-platform-uaa-key
      - name: srv-api
      - name: skillforge-training-platform-service-html5-apps-repo-host
        parameters:
          service-key:
            name: skillforge-training-platform-html5-apps-repo-host-key
      - name: skillforge-training-platform-service-destination
        parameters:
          content-target: true
  - name: skillforge-training-platform-launchpad
    type: html5
    path: build/launchpad
    build-parameters:
      builder: custom
      commands:
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - bash -c "cd dist && npx bestzip ../../../build/dist/launchpad.zip *"
        - rm -rf dist
      _artifactName: launchpad.zip
      supported-platforms: []
      build-result: ../../build/dist
  - name: skillforge-training-platform-aux-ui-deployer
    type: com.sap.application.content
    path: build/ui-deployer
    build-parameters:
      build-result: resources
      requires:
        - name: skillforge-training-platform-saplearningcenter.saplearningcenter
          artifacts:
            - saplearningcentersaplearningcenter.zip
          target-path: resources
        - name: skillforge-training-platform-launchpad
          artifacts:
            - launchpad.zip
          target-path: resources
    requires:
      - name: skillforge-training-platform-service-html5-apps-repo-host
        parameters:
          content-target: true
resources:
  - type: org.cloudfoundry.managed-service
    name: skillforge-training-platform-service-uaa
    parameters:
      service: xsuaa
      service-plan: application
      service-name: skillforge-training-platform-uaa
      path: xs-security.json
      config:
        oauth2-configuration:
          redirect-uris:
            - https://${subdomain}.launchpad.${default-domain}/login/*
            - https://${subdomain}.${default-domain}/login/*
          credential-types:
            - binding-secret
            - x509
        xsappname: skillforge-training-platform-${space}
        role-collections:
          - description: Admin
            name: skillforge-training-platform-Admin-${space}
            role-template-references:
              - $XSAPPNAME.Admin
          - description: Manager
            name: skillforge-training-platform-Manager-${space}
            role-template-references:
              - $XSAPPNAME.Manager
          - description: User
            name: skillforge-training-platform-User-${space}
            role-template-references:
              - $XSAPPNAME.User
          - description: Lead
            name: skillforge-training-platform-Lead-${space}
            role-template-references:
              - $XSAPPNAME.Lead
  - type: org.cloudfoundry.managed-service
    name: skillforge-training-platform-service-db
    parameters:
      service: hana
      service-plan: hdi-shared
      service-name: skillforge-training-platform-db
  - type: org.cloudfoundry.managed-service
    name: skillforge-training-platform-service-destination
    parameters:
      service: destination
      service-plan: lite
      service-name: skillforge-training-platform-destination
      config:
        HTML5Runtime_enabled: true
        version: 1.0.0
  - type: org.cloudfoundry.user-provided-service
    name: skillforge-training-platform-service-metadata
    parameters:
      service: metadata
      service-plan: standard
      service-name: skillforge-training-platform-metadata
      config:
        default-domain: ${default-domain}
  - type: org.cloudfoundry.managed-service
    name: skillforge-training-platform-service-connectivity
    parameters:
      service: connectivity
      service-plan: lite
      service-name: skillforge-training-platform-connectivity
  - type: org.cloudfoundry.managed-service
    name: skillforge-training-platform-service-logs
    parameters:
      service: application-logs
      service-plan: lite
      service-name: skillforge-training-platform-logs
  - type: org.cloudfoundry.managed-service
    name: skillforge-training-platform-service-html5-apps-repo-host
    parameters:
      service: html5-apps-repo
      service-plan: app-host
      service-name: skillforge-training-platform-html5-apps-repo-host
